# Generated by Django 5.1.6 on 2025-02-25 10:52

from django.db import migrations

def populate_plan_choice(apps, schema_editor):
    # We can't import the PlanChoice model directly as it may be a newer
    # version than this migration excepts. We use the historical version.
    PlanChoice = apps.get_model('client', 'PlanChoice')
    PlanChoice.objects.create(
        plan = 'ST',
        name = 'Standard',
        cost = '3.00',
        is_active = True,
        description1 = 'Get access to standard articles and reports',
        description2 = 'Limited Access',
        external_plan_id = 'P-5JF74700F7609213LM64LLLI',
        external_api_url = 'https://www.paypal.com/sdk/js?client-id=AQEB8ulIdxr2ZJuGkn2ZS-Cp_wkkzDvj5NCjq7yinNFp9fqMWbd7n1qdxOalD7Cu10JFS5tl12yrfUx7&vault=true&intent=subscription',
        external_style_json = """{
    "shape": "pill",
    "color": "silver",
    "layout": "vertical",
    "label": "subscribe"
}
"""
    )
    PlanChoice.objects.create(
        plan = 'PR',
        name = 'Premium',
        cost = '9.00',
        is_active = True,
        description1 = 'Highly regarded premium articles and reports',
        description2 = 'Premium Subscription',
        external_plan_id = 'P-81653453GU063804XM66IQCQ',
        external_api_url = 'https://www.paypal.com/sdk/js?vault=true&intent=subscription',
        external_style_json = """{
    "shape": "pill",
    "color": "gold",
    "layout": "vertical",
    "label": "subscribe"
}
"""
    )

class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_planchoice_alter_subscription_cost'),
    ]

    operations = [
        migrations.RunPython(populate_plan_choice)
    ]
