# Generated by Django 5.1.6 on 2025-03-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_rename_plan_planchoice_plan_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='external_subscription_id',
            field=models.CharField(max_length=255, unique=True, verbose_name='External subscription ID'),
        ),
    ]
