# Generated by Django 5.1.5 on 2025-02-11 10:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='dateJoined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
